### ISSUE TITLE
Graceful error notification when worker crashes

### ISSUE THREAD

**Issue by novemberborn** [gustavnikolaj/linter-js-standard-engine#24]
I haven't checked quite what happens when the worker crashes (e.g. because the linter could not be found) but there should be a graceful error notification.

Ideally in the linter bar below the editor (where linting errors are show), rather than as a full-blown notification. Those get quite annoying when opening files in a project where dependencies haven't yet been installed.

**Comment by novemberborn** [comment]
Oh never mind, #23 tackles this!

**Comment by gustavnikolaj** [comment]
Might still be worth it to wrap `child.send` in try/catch to handle the case where the worker did crash. #23 tackles the most obvious error, but we could still end up spamming the user with errors if the linter they use crash.

https://github.com/gustavnikolaj/linter-js-standard-engine/blob/98b8771e4950df14f0a18b6fd3b9207333d5c84b/lib/getLinter.js#L38-L41
