### ISSUE TITLE
Consider warning about linter not being installed

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/linter-js-standard-engine#25]
Any errors that is relayed from trying to require the linter in the worker is being supressed now.

We might want to change that because...

- When we get a `MODULE_NOT_FOUND` error, it means that the linter was unavailable. Reporting this only once - or only once every few minutes - would allow users to realize that instead of just being puzzled about why it suddenly did not work. (This just happened to me, as I forgot that I had `rm -r node_modules/standard` while testing the plugin friday)

- If there's an error in the module itself (when it is anything but a `MODULE_NOT_FOUND` error) it is really hard for the user to realize what the problem is. At least until they go run their linter at the command line.

The problem is that since we lint very aggressively, a user will get drowned in error notifications unless we limit them. But maybe there is a sweet spot in between showing all of them, and hiding everything.

---

Maybe we can abuse the linter report, and return an almost empty report with a single fatal error at the first character of the first line, telling them that their linter is defunct?

**Comment by novemberborn** [comment]
> Maybe we can abuse the linter report, and return an almost empty report with a single fatal error at the first character of the first line, telling them that their linter is defunct?

👍
