### ISSUE TITLE
Update to new Linter API

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/linter-js-standard-engine#27]
https://github.com/steelbrain/linter/blob/master/docs/guides/upgrading-to-standard-linter-v2.md

Some hope that this might solve #7

**Comment by novemberborn** [comment]
Linter 2.0 is now out.

**Comment by novemberborn** [comment]
http://steelbrain.me/2017/03/13/linter-v2-released.html has a good overview.
