### ISSUE TITLE
Don't walk the file system for package.json files on each lint run

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/linter-js-standard-engine#3]
This should be done by memoizing the `findOptions` method in `lib/findOptions.js`.

**Comment by trodrigues** [comment]
I was going to open an issue when I noticed this here.

I was working on a very small sample project with no package.json, and Atom started crashing every time I was editing a JS file. I also noticed an Atom Helper process eating away all the CPU.

After a lot of plugin disabling and enabling I found this one to be the culprit, and indeed if I add a package.json it stops showing that behavior.

I was having a quick look through the code and it seems like even though this use case is handled, it doesn't remember that the file wasn't found and it's always trying to find it again.

Would simply caching the result of [firstPackageJson](https://github.com/gustavnikolaj/linter-js-standard-engine/blob/master/lib/findOptions.js#L68) be enough to avoid that?

**Comment by gustavnikolaj** [comment]
First of all, I'm sorry for the inconvenience I've caused you!

Yes, caching the results would indeed fix this. The [lru-cache](https://www.npmjs.com/package/lru-cache) is a great fit, as we can easily make sure that we don't keep irrellevant files in the cache. 

The downside of doing that is, that the linter won't pick up on changes to the package.json file (or at least not new package.json files added to the three- I don't remember how it works specifically). That means that we would have to restart the editor in those cases.

To counter that, we could memoize only the last file linted. That would make sure that it doesn't go into the abyss when looking for one that doesn't exist...

Which path seems most beneficial to you?

**Comment by trodrigues** [comment]
No worries :)

Yeah, that's also what I thought, that it would then require a restart if you did add a package.json.

I think for that case, showing a warning for the first time would at least let people know they'd have to restart for a detection, although I also see how that could become annoying.

I'm not entirely sure I understand the second solution you propose, but if I do, wouldn't that mean that every time you switch files it would try and look for it again?

Other similar plugins like linter-eslint and linter-jshint seem to detect when a file is added and start linting, but they don't attempt to do anything if a config file is not there (and there is an option to disable the plugin if there is no file).

I had a quick look through the code of linter-jshint and it seems like it uses some helpers from the [atom-linter](https://github.com/steelbrain/atom-linter) package: https://github.com/AtomLinter/linter-jshint/blob/master/lib/main.js#L104

Other than that the approach of always trying to find the file seems to be the same you're following.

I'm wondering if using these helpers would be enough to fix the issue?

**Comment by gustavnikolaj** [comment]
I couldn't find any documentation of the Helper function they required from atom-linter - and couldn't find the source for it either in the atom-linter package... I think we can get around most of it pretty easily, by caching the last result - if the input is the same - just return the same result. That would mean that we check for the configuration file each time you open a new file - or change tabs. It should give the right result each time - chances are that you are changing to the package.json file when you change it :-)

Would you be up for trying to send a PR?

**Comment by trodrigues** [comment]
Yeah I'm gonna give it a try and see if I can fix it :)

**Comment by trodrigues** [comment]
So as I started looking a the code in order to make the fix I noticed something and it turned out the fix was much easier than expected. See https://github.com/gustavnikolaj/linter-js-standard-engine/pull/11 :)

**Comment by gustavnikolaj** [comment]
I'll let this issue stick around, as I still want to do some polishing to this at some point :-) Thanks for your help!

**Comment by taoeffect** [comment]
Should this issue be closed?

**Comment by novemberborn** [comment]
@taoeffect the code has changed a bit since this issue was raised, but as far as I can tell we're still not caching anything.

For what it's worth I think we should cache the `package.json` path, but not its contents. We currently use `read-pkg-up` but it's easy to use its underlying modules instead. See [its source](https://github.com/sindresorhus/read-pkg-up/blob/3b8a594ab581f000f705e43e8abdb1a23e8822f2/index.js).
