### ISSUE TITLE
Bump Node version

### ISSUE THREAD

**Issue by novemberborn** [gustavnikolaj/linter-js-standard-engine#35]
Atom v1.12.0 ships with Node.js v6.3.0. Let's move our test targets to that version.

**Comment by gustavnikolaj** [comment]
Should we update the `engines` field in package json as well?

https://github.com/gustavnikolaj/linter-js-standard-engine/blob/271c13d6cc922f3a6adcfcfb6749bd60e526c322/package.json#L13

**Comment by novemberborn** [comment]
Yup.

**Comment by gustavnikolaj** [comment]
Added that as well. Not publishing a new version yet, since the only changes since 1.0.2 is these commits updating the test target. Next version will require at least atom 1.12.0.
