### ISSUE TITLE
Seems to ignore eslint plugins and "globals"?

### ISSUE THREAD

**Issue by taoeffect** [gustavnikolaj/linter-js-standard-engine#36]
With [`eslint-plugin-flowtype`](https://github.com/gajus/eslint-plugin-flowtype) installed and package.json config containing:

```json
  "standard": {
    "parser": "babel-eslint",
    "plugins": [
      "flowtype"
    ],
    "extends": [
      "plugin:flowtype/recommended"
    ]
  },
```

I still get `'X' is not defined` warnings, which shouldn't happen because of [`define-flow-type`](https://github.com/gajus/eslint-plugin-flowtype#define-flow-type)

Strangely, even command line `standard` gives me that, but OTOH it respects manually added types via `"globals": ["Type1", "Type2" ...]`, but this linter does not.

**Comment by gustavnikolaj** [comment]
I haven't used flow before. Could you provide a example repo where this error occurs? That would make it easier for me to dig in. :-)

**Comment by novemberborn** [comment]
This plugin just calls `standard` in a child process. Besides #28 it behaves just like a CLI invocation of `standard` itself.

You can't use `extends` in the `standard` config stanza. You'll have to make your own [`standard-engine`](https://github.com/Flet/standard-engine) implementation. As an example, here's mine: https://github.com/novemberborn/as-i-preach.

I'm not sure why `globals` would behave differently though. Any chance you're in a monorepo and have different `package.json` files?

**Comment by taoeffect** [comment]
I've decided to manually import types via `import type`. It's probably better this way anyway, more explicit. I must admit that my plate is too full to create an example repo, and so between that and my finding an alternative solution, I'll close this issue. Thanks for the responses guys.
