### ISSUE TITLE
Don't flood the user with errors

### ISSUE THREAD

**Issue by novemberborn** [gustavnikolaj/linter-js-standard-engine#40]
Ensure only one notification is displayed per error type (probably identified by its message). Only add a new notification once the previous notification for that type has been dismissed.

Add a button to disable this package for the current window. Perhaps we'd need a command so users can reenable it without having to reload the window.

**Comment by gustavnikolaj** [comment]
:+1:

Also, more user friendly error messages would be nice. Asking people to npm install when we get MODULE_NOT_FOUND etc.
