### ISSUE TITLE
Require opt-in before linting a new project

### ISSUE THREAD

**Issue by novemberborn** [gustavnikolaj/linter-js-standard-engine#41]
I'm uncomfortable with how this package executes code simply when editing a file in a directory. Perhaps we can ask the user whether they want to enable linting for the current project (as identified by the location of the `package.json` file). Options would be to "lint this project" and "lint this and all future projects".

**Comment by gustavnikolaj** [comment]
I prefer on-the-fly linting, but I know that I am probably a minority :-) Would a default setting of lint-on-save make you more comfortable?

I would be okay with some opt-in of a kind - preferably it would prompt the user when it detects a compatible linter, and not hidden in settings. 

I guess my reasoning was that if you have it installed and listed in package.json, it is a passive opt-in - but I see your point.

**Comment by novemberborn** [comment]
My concern is cloning somebody else's project and accidentally running their code, without having run `npm install` or anything else that I know causes code execution.

The prompt would come up when linting would normally take place. At that point you could enable it for all future projects, with a way to reset authorizations in the settings. So if you trust all code you open then you only have to authorize once for all projects and the linter will behave as it does now.
