### ISSUE TITLE
Compatibility with standard-engine@6

### ISSUE THREAD

**Issue by novemberborn** [gustavnikolaj/linter-js-standard-engine#45]
`standard-engine@6` [makes `lintText()` synchronous](https://github.com/Flet/standard-engine/pull/157). We should support both forms.

**Comment by gustavnikolaj** [comment]
My initial idea is to just to check the `.length` of the `lintText` method. 

I'll land a quick fix doing it that way for now, but if you can think of better ways of checking, or I come up with one later, we should get back around to it.

**Comment by novemberborn** [comment]
I think that's coupling too much to this implementation of `standard-engine`'s interface. We could just pass a callback and use the return value if it exists.

**Comment by gustavnikolaj** [comment]
Released in [1.3.0](https://github.com/gustavnikolaj/linter-js-standard-engine/releases/tag/v1.3.0).
