### ISSUE TITLE
Submit a PR for feross/standard's README mentioning this plugin.

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/linter-js-standard-engine#47]
1. Do we want to do this?

2. Do we have any features or bugs we should have fixed before doing it?

**Comment by gustavnikolaj** [comment]
We should probably send a similar request to standard-engine, to raise awareness for those of us who maintain our own standard-engine based linters.

**Comment by novemberborn** [comment]
👍

**Comment by gustavnikolaj** [comment]
PR for standard submitted: https://github.com/feross/standard/pull/886

**Comment by gustavnikolaj** [comment]
Issue opened in standard-engine: https://github.com/Flet/standard-engine/issues/162

**Comment by Flet** [comment]
I also suggest sending a PR to http://github.com/feross/awesome-standard

**Comment by gustavnikolaj** [comment]
Great idea @Flet :-) Will do!

**Comment by gustavnikolaj** [comment]
PR for awesome-standard submitted: https://github.com/feross/awesome-standard/pull/13

**Comment by gustavnikolaj** [comment]
All PR's merged :-)
