### ISSUE TITLE
Doesn't seem to be doing anything

### ISSUE THREAD

**Issue by ricardograca** [gustavnikolaj/linter-js-standard-engine#58]
I followed the instructions and installed this package. I have `standard` in the `devDependencies` section of my `package.json` file. No linting errors or warnings are displayed in a file that has errors.

I can confirm that running `standard` manually will report the expected errors.

Atom 1.27.2
Ubuntu 16.04
linter-js-standard-engine 2.2.0

**Comment by ricardograca** [comment]
After further investigation this is only an issue when using the experimental Tree Sitter Parsers options of Atom.

**Comment by sonicdoe** [comment]
#59 adds support for Atom’s Tree-sitter parsing system. In the meantime, you could manually add `javascript` to the list of grammar scopes in linter-js-standard-engine’s settings.

**Comment by gustavnikolaj** [comment]
@sonicdoe's fix has been merged and released as v2.3.0. Thanks for the report and thanks for the fix :-)
