### ISSUE TITLE
Handle multiple tabs with the same file.

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/linter-js-standard-engine#7]
Currently this can cause funny situations where the linting output gets stuck and out of date.

**Comment by gustavnikolaj** [comment]
I noticed a similar problem with the linter-eslint plugin. Maybe it's just a problem in atom or the atom-linter project?

**Comment by gustavnikolaj** [comment]
https://github.com/steelbrain/linter/issues/871

**Comment by gustavnikolaj** [comment]
https://github.com/steelbrain/linter/pull/873

**Comment by novemberborn** [comment]
This should be fixed with #48.
